// Auto-sliding hero. Slides come from slides.js (generated by tools/blur_boudoir_photos.py).
(() => {
  const INTERVAL = 5200;
  const slides = window.SLIDES || [];
  const track = document.querySelector('.track');
  const dots = document.querySelector('.dots');
  if (!track || !slides.length) return;

  const root = document.documentElement.style;
  root.setProperty('--interval', `${INTERVAL}ms`);

  // Size the frame to the photos' own proportions (portrait or landscape).
  const probe = new Image();
  probe.onload = () => root.setProperty('--ar', `${probe.naturalWidth} / ${probe.naturalHeight}`);
  probe.src = slides[0];

  const make = (src, i) => {
    const el = document.createElement('div');
    el.className = 'slide';
    const img = new Image();
    img.src = src;
    img.alt = '';
    img.decoding = 'async';
    img.draggable = false;
    if (i > 0) img.loading = 'lazy';
    el.appendChild(img);
    return el;
  };

  slides.forEach((src, i) => track.appendChild(make(src, i)));
  // Clone of the first slide at the end so the loop never slides backwards.
  if (slides.length > 1) track.appendChild(make(slides[0], 1));

  const marks = slides.map(() => dots.appendChild(document.createElement('i')));

  let index = 0;
  let timer = null;

  const mark = (i) => {
    marks.forEach((m) => m.classList.remove('on'));
    // Force reflow so the fill animation restarts.
    void marks[i].offsetWidth;
    marks[i].classList.add('on');
  };

  const go = (i) => {
    index = i;
    track.style.transform = `translateX(${-100 * index}%)`;
    mark(index % slides.length);
  };

  track.addEventListener('transitionend', () => {
    if (index === slides.length) {
      track.classList.add('no-anim');
      go(0);
      void track.offsetWidth;
      track.classList.remove('no-anim');
    }
  });

  const start = () => {
    if (slides.length < 2 || timer) return;
    timer = setInterval(() => go(index + 1), INTERVAL);
  };
  const stop = () => { clearInterval(timer); timer = null; };

  document.addEventListener('visibilitychange', () => (document.hidden ? stop() : start()));
  document.addEventListener('contextmenu', (e) => {
    if (e.target.closest('.frame')) e.preventDefault();
  });

  mark(0);
  start();
})();
