// Generated by tools/blur_boudoir_photos.py. Do not edit by hand.
window.SLIDES = [
  "/images/boudoirfotograf-malmo-01.jpg",
  "/images/boudoirfotograf-malmo-02.jpg",
  "/images/boudoirfotograf-malmo-03.jpg",
  "/images/boudoirfotograf-malmo-04.jpg"
];
